### Hello
GET http://localhost:8080/hello
Content-Type: application/json



### Hello QueryString
GET http://localhost:8080/hello?name=spring-server
Content-Type: application/json


### Users
GET http://localhost:8080/users
Content-Type: application/json